language: c
sudo: required
dist: bionic
os: linux

script:
#  - bash -ex deploy.sh
 - sudo apt-get update
 - sudo apt-get -y install python3 python3-setuptools python3-pip wget patchelf fakeroot gnupg2 libglib2.0-bin file desktop-file-utils libgdk-pixbuf2.0-dev librsvg2-dev zsync
 - sudo mkdir -p /usr/share/icons/hicolor/scalable/ ; sudo cp wine.svg /usr/share/icons/hicolor/scalable/
 - sudo pip3 install appimage-builder
 - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage && chmod +x appimagetool-x86_64.AppImage
 - mv appimagetool-x86_64.AppImage appimagetool && cp appimagetool /home/travis/bin && ls -al && ls -al /home/travis/bin

after_success:
 - appimage-builder --skip-tests --recipe wine-stable.yml
 - appimage-builder --skip-tests --recipe wine-devel.yml
 - appimage-builder --skip-tests --recipe wine-staging.yml
  # uploadtool
 - wget -c https://raw.githubusercontent.com/probonopd/uploadtool/8142d461aba7b92a058116fe5ee75be438b75fa4/upload.sh
 - bash upload.sh ./*.AppImage*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^release-[0-9a-z\-]*/
    - /^(?i:untagged)-.*$/
