# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Build at 00:00 on every 12th day-of-month.
  schedule:
    - cron: "0 0 */12 * *"
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths-ignore: [ '**/README.md' ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ '**/README.md' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-stable-arm:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3

        - name: Prerequisites
          run: |
            wget -q "https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.0.3/appimage-builder-1.0.3-x86_64.AppImage" -O appimage-builder ; chmod +x appimage-builder ; sudo mv appimage-builder /usr/bin
            mkdir -p /usr/share/icons/hicolor/scalable/ ; cp wine.svg /usr/share/icons/hicolor/scalable/

        # Runs a set of commands using the runners shell
        - name: Build appimage
          run: |
            # add dir dist
            mkdir dist

            appimage-builder --recipe wine-stable-arm.yml
            mv *AppImage* dist/.

        - name: Upload artifact
          uses: actions/upload-artifact@v1.0.0
          with:
            name: wine-stable-arm-continuous-armhf.AppImage
            path: 'dist'

  build-stable-arm64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Prerequisites
        run: |
          wget -q "https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.0.3/appimage-builder-1.0.3-x86_64.AppImage" -O appimage-builder ; chmod +x appimage-builder ; sudo mv appimage-builder /usr/bin
          mkdir -p /usr/share/icons/hicolor/scalable/ ; cp wine.svg /usr/share/icons/hicolor/scalable/

      # Runs a set of commands using the runners shell
      - name: Build appimage
        run: |
          # add dir dist
          mkdir dist

          appimage-builder --recipe wine-stable-arm64.yml
          mv *AppImage* dist/.

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: wine-stable-arm64-continuous-aarch64.AppImage
          path: 'dist'

  build-devel-arm:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3

        - name: Prerequisites
          run: |
            wget -q "https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.0.3/appimage-builder-1.0.3-x86_64.AppImage" -O appimage-builder ; chmod +x appimage-builder ; sudo mv appimage-builder /usr/bin
            mkdir -p /usr/share/icons/hicolor/scalable/ ; cp wine.svg /usr/share/icons/hicolor/scalable/

        # Runs a set of commands using the runners shell
        - name: Build appimage
          run: |
            # add dir dist
            mkdir dist

            appimage-builder --recipe wine-devel-arm.yml
            mv *AppImage* dist/.

        - name: Upload artifact
          uses: actions/upload-artifact@v1.0.0
          with:
            name: wine-devel-arm-continuous-armhf.AppImage
            path: 'dist'

  build-devel-arm64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Prerequisites
        run: |
          wget -q "https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.0.3/appimage-builder-1.0.3-x86_64.AppImage" -O appimage-builder ; chmod +x appimage-builder ; sudo mv appimage-builder /usr/bin
          mkdir -p /usr/share/icons/hicolor/scalable/ ; cp wine.svg /usr/share/icons/hicolor/scalable/

      # Runs a set of commands using the runners shell
      - name: Build appimage
        run: |
          # add dir dist
          mkdir dist

          appimage-builder --recipe wine-devel-arm64.yml
          mv *AppImage* dist/.

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: wine-devel-arm64-continuous-aarch64.AppImage
          path: 'dist'

  release-stable-arm:
    needs: [build-stable-arm]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v1
        with:
          name: wine-stable-arm-continuous-armhf.AppImage

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Continuous build (stable) arm
          automatic_release_tag: continuous-stable-arm
          prerelease: false
          draft: false
          files: |
            wine-stable-arm-continuous-armhf.AppImage
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  release-stable-arm64:
      needs: [build-stable-arm64]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: wine-stable-arm64-continuous-aarch64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build (stable) arm64
            automatic_release_tag: continuous-stable-arm64
            prerelease: false
            draft: false
            files: |
              wine-stable-arm64-continuous-aarch64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}

  release-devel-arm:
      needs: [build-devel-arm]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: wine-devel-arm-continuous-armhf.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build (devel) arm
            automatic_release_tag: continuous-devel-arm
            prerelease: false
            draft: false
            files: |
              wine-devel-arm-continuous-armhf.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}

  release-devel-arm64:
      needs: [build-devel-arm64]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: wine-devel-arm64-continuous-aarch64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build (devel) arm64
            automatic_release_tag: continuous-devel-arm64
            prerelease: false
            draft: false
            files: |
              wine-devel-arm64-continuous-aarch64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
